version: "2.27.1-desktop.1"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/app
